// src/components/Contact.vue
<script setup>
import { ref } from 'vue'

const email = "devan.smit2007@gmail.com"
const isCopied = ref(false)
const contactSection = ref(null)

const copyEmail = () => {
  navigator.clipboard.writeText(email).then(() => {
    isCopied.value = true
    setTimeout(() => {
      isCopied.value = false
    }, 2000)
  }).catch(err => {
    console.error('Failed to copy: ', err)
  })
}
</script>

<template>
  <section id="contact" class="contact section" ref="contactSection">
    <div class="section-container">
      <div class="section-title-group">
        <span class="section-label">Connect</span>
        <h2 class="section-title">Get In Touch</h2>
      </div>
      
      <div class="contact-content card fade-in">
        <div class="contact-header">
          <h3 class="contact-headline">Ready to start something <span>new</span>?</h3>
          <p class="contact-text">
            Whether you have a specific project in mind or just want to explore 
            how we could work together, I'd love to hear from you.
          </p>
        </div>

        <div class="contact-methods">
          <div class="email-badge" @click="copyEmail">
            <div class="email-info">
              <span class="badge-label">Email me at</span>
              <span class="badge-address">{{ email }}</span>
            </div>
            <button class="badge-action" :class="{ 'copied': isCopied }">
              <span v-if="!isCopied">Copy</span>
              <span v-else>Copied!</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                <rect v-if="!isCopied" x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                <path v-if="!isCopied" d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                <polyline v-else points="20 6 9 17 4 12"></polyline>
              </svg>
            </button>
          </div>
        </div>

        <div class="contact-social">
          <a href="https://www.linkedin.com/in/devan-smit-190480385/" target="_blank" rel="noopener noreferrer" class="social-link">
            LinkedIn
          </a>
          <a href="https://github.com/Light-not-found" target="_blank" rel="noopener noreferrer" class="social-link">
            GitHub
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.contact {
  padding: 80px 0;
  position: relative;
  overflow: hidden;
}

.contact-content {
  max-width: 800px;
  margin: 0 auto;
  padding: 4rem 3rem;
  background: var(--bg-color-alt);
  border: 1px solid var(--border-color);
  text-align: center;
  position: relative;
  z-index: 1;
}

.contact-headline {
  font-size: 2.25rem;
  margin-bottom: 1rem;
  letter-spacing: -1px;
}

.contact-headline span {
  color: var(--accent-primary);
}

.contact-text {
  color: var(--text-secondary);
  max-width: 500px;
  margin: 0 auto 3rem;
  line-height: 1.6;
}

.contact-methods {
  display: flex;
  justify-content: center;
  margin-bottom: 2.5rem;
}

.email-badge {
  display: flex;
  align-items: center;
  gap: 1.5rem;
  padding: 0.5rem 0.5rem 0.5rem 1.75rem;
  background: rgba(255, 255, 255, 0.02);
  border: 1px solid var(--border-color);
  border-radius: 100px;
  cursor: pointer;
  transition: all var(--transition-base);
}

.email-badge:hover {
  border-color: var(--accent-primary);
  background: rgba(255, 255, 255, 0.04);
}

.email-info {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
}

.badge-label {
  font-size: 0.65rem;
  font-weight: 700;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.badge-address {
  font-weight: 600;
  font-size: 1rem;
}

.badge-action {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  padding: 0.75rem 1.5rem;
  background: var(--text-primary);
  color: var(--bg-color);
  border: none;
  border-radius: 100px;
  font-weight: 700;
  font-size: 0.85rem;
  cursor: pointer;
  transition: all 0.2s;
}

.badge-action.copied {
  background: var(--accent-primary);
  color: #fff;
}

.contact-social {
  display: flex;
  justify-content: center;
  gap: 2rem;
}

.social-link {
  color: var(--text-secondary);
  font-weight: 500;
  font-size: 0.95rem;
  position: relative;
}

.social-link::after {
  content: '';
  position: absolute;
  bottom: -4px;
  left: 0;
  width: 0;
  height: 1px;
  background: var(--accent-primary);
  transition: width 0.3s;
}

.social-link:hover {
  color: var(--text-primary);
}

.social-link:hover::after {
  width: 100%;
}


@media (max-width: 768px) {
  .contact-content {
    padding: 3rem 1.5rem;
  }
  
  .contact-headline {
    font-size: 1.75rem;
  }
  
  .email-badge {
    flex-direction: column;
    padding: 1.5rem;
    border-radius: 20px;
    width: 100%;
    gap: 1rem;
    text-align: center;
  }
  
  .email-info {
    align-items: center;
  }
  
  .badge-action {
    width: 100%;
    justify-content: center;
  }
}
</style>

// src/components/Contact.tsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Copy, Check } from 'lucide-react';

const Contact: React.FC = () => {
  const email = "devan.smit2007@gmail.com";
  const [isCopied, setIsCopied] = useState(false);

  const copyEmail = () => {
    navigator.clipboard.writeText(email).then(() => {
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }).catch(err => {
      console.error('Failed to copy: ', err);
    });
  };

  return (
    <section id="contact" className="py-32 relative overflow-hidden bg-zinc-900/10">
      {/* Seamless Grid Pattern Overlay */}
      <div className="absolute inset-0 bg-grid-pattern mask-fade-y pointer-events-none opacity-30" />
      
      <div className="max-w-4xl mx-auto px-8 relative z-10 text-center">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
          className="flex flex-col items-center gap-3 mb-16 relative"
        >
          <span className="text-xs text-blue-500 bg-blue-500/10 px-4 py-2 border border-blue-500/20 rounded-full tracking-widest uppercase font-bold">
            Connect
          </span>
          <h2 className="text-[clamp(2.5rem,6vw,3.5rem)] m-0 leading-tight text-gradient font-heading">
            Get In Touch
          </h2>
        </motion.div>
        
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="glass p-12 md:p-20 rounded-3xl flex flex-col items-center max-w-4xl mx-auto"
        >
          <h3 className="text-[clamp(2rem,4vw,3rem)] tracking-tight mb-6 font-heading">
            Ready to start something <span className="text-blue-500">new</span>?
          </h3>
          <p className="text-zinc-400 text-lg max-w-xl mx-auto mb-12">
            Whether you have a specific project in mind or just want to explore 
            how we could work together, I'd love to hear from you.
          </p>

          <div className="flex justify-center mb-12 w-full">
            <div 
              className="flex flex-col md:flex-row items-center gap-4 md:gap-6 p-4 md:py-2 md:pl-8 md:pr-2 bg-white/5 border border-white/10 rounded-3xl md:rounded-full cursor-pointer transition-all duration-300 hover:border-white/30 hover:-translate-y-1 hover:bg-white/10 w-full md:w-auto"
              onClick={copyEmail}
            >
              <div className="flex flex-col items-center md:items-start text-center md:text-left">
                <span className="text-[0.7rem] font-bold text-zinc-500 uppercase tracking-[0.1em]">
                  Email me at
                </span>
                <span className="font-semibold text-lg">
                  {email}
                </span>
              </div>
              <button 
                className={`flex items-center justify-center gap-2 px-6 py-3 md:py-4 rounded-full font-bold text-sm w-full md:w-auto transition-colors duration-300 ${
                  isCopied ? 'bg-blue-500 text-white' : 'bg-white text-zinc-950'
                }`}
              >
                {!isCopied ? (
                  <>
                    <span>Copy</span>
                    <Copy size={16} strokeWidth={2.5} />
                  </>
                ) : (
                  <>
                    <span>Copied!</span>
                    <Check size={16} strokeWidth={2.5} />
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="flex justify-center gap-10">
            <a 
              href="https://www.linkedin.com/in/devan-smit-190480385/" 
              target="_blank" 
              rel="noopener noreferrer" 
              className="text-zinc-400 font-semibold text-lg relative pb-1 transition-colors hover:text-white group"
            >
              LinkedIn
              <span className="absolute bottom-0 left-0 w-0 h-[2px] bg-blue-500 transition-all duration-300 group-hover:w-full" />
            </a>
            <a 
              href="https://github.com/Light-not-found" 
              target="_blank" 
              rel="noopener noreferrer" 
              className="text-zinc-400 font-semibold text-lg relative pb-1 transition-colors hover:text-white group"
            >
              GitHub
              <span className="absolute bottom-0 left-0 w-0 h-[2px] bg-blue-500 transition-all duration-300 group-hover:w-full" />
            </a>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default Contact;
