// src/components/Footer.tsx
import React, { useEffect, useState } from 'react';
import { ArrowUp } from 'lucide-react';
import Magnetic from './Magnetic';

const Footer: React.FC = () => {
  const [time, setTime] = useState<string>('');

  useEffect(() => {
    const updateClock = () => {
      const options: Intl.DateTimeFormatOptions = {
        timeZone: 'Europe/Amsterdam',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false
      };
      const formatter = new Intl.DateTimeFormat('en-US', options);
      setTime(formatter.format(new Date()));
    };

    updateClock();
    const interval = setInterval(updateClock, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <footer className="relative py-12 px-8 bg-zinc-900/30 border-t border-white/5 overflow-hidden">
      {/* Background Subtle Grid */}
      <div className="absolute inset-0 bg-grid-pattern mask-fade-y pointer-events-none opacity-20" />

      <div className="max-w-6xl mx-auto relative z-10">
        <div className="flex flex-col md:flex-row justify-between items-center gap-8 text-zinc-500 text-sm">
          
          {/* Left: Amsterdam time & location */}
          <div className="flex items-center gap-6 font-mono text-[10px] sm:text-xs tracking-wider uppercase">
            <div className="flex items-center gap-2">
              <span className="flex h-1.5 w-1.5 relative">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-blue-500"></span>
              </span>
              <span>Amsterdam, NL</span>
            </div>
            <div>
              {time ? `${time} GMT+2` : 'Loading...'}
            </div>
          </div>

          {/* Center: Navigation Links */}
          <div className="flex flex-wrap justify-center gap-6 sm:gap-8 text-[10px] sm:text-xs font-semibold uppercase tracking-widest">
            <a href="#about" className="text-zinc-400 hover:text-white transition-colors duration-300">About</a>
            <a href="#skills" className="text-zinc-400 hover:text-white transition-colors duration-300">Skills</a>
            <a href="#projects" className="text-zinc-400 hover:text-white transition-colors duration-300">Projects</a>
            <a href="https://www.linkedin.com/in/devan-smit-190480385/" target="_blank" rel="noopener noreferrer" className="text-zinc-400 hover:text-white transition-colors duration-300">LinkedIn</a>
            <a href="https://github.com/Light-not-found" target="_blank" rel="noopener noreferrer" className="text-zinc-400 hover:text-white transition-colors duration-300">GitHub</a>
          </div>

          {/* Right: Copyright & back to top */}
          <div className="flex items-center gap-6">
            <p className="m-0 font-medium text-xs sm:text-sm">&copy; {new Date().getFullYear()} — DS</p>
            <Magnetic pullFactor={0.25}>
              <a 
                href="#" 
                className="flex items-center justify-center w-10 h-10 rounded-full border border-white/10 text-white transition-all duration-300 hover:border-white hover:bg-white/5"
                aria-label="Back to top"
              >
                <ArrowUp size={16} strokeWidth={2.5} />
              </a>
            </Magnetic>
          </div>

        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="section-container">
      <div class="footer-content">
        <div class="footer-left">
          <a href="#" class="logo">D<span>S</span></a>
          <nav class="footer-nav">
            <a href="#about">About</a>
            <a href="#skills">Skills</a>
            <a href="#projects">Projects</a>
            <a href="#contact">Contact</a>
          </nav>
        </div>
        
        <div class="footer-right">
          <div class="footer-social">
            <a href="https://github.com/Light-not-found" target="_blank" rel="noopener noreferrer" title="GitHub">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
            </a>
            <a href="https://www.linkedin.com/in/devan-smit-190480385/" target="_blank" rel="noopener noreferrer" title="LinkedIn">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>
            </a>
          </div>
          <p class="copyright">&copy; 2026 Devan Smit.</p>
        </div>
      </div>
    </div>
  </footer>
</template>

<style scoped>
.footer {
  padding: 30px 0;
  background-color: var(--bg-color);
  border-top: 1px solid var(--border-color);
}

.footer-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.footer-left, .footer-right {
  display: flex;
  align-items: center;
  gap: 2.5rem;
}

.footer-nav {
  display: flex;
  gap: 1.5rem;
}

.footer-nav a {
  color: var(--text-secondary);
  font-size: 0.85rem;
  font-weight: 500;
  transition: color 0.2s;
}

.footer-nav a:hover {
  color: var(--text-primary);
}

.footer-social {
  display: flex;
  gap: 1rem;
}

.footer-social a {
  color: var(--text-muted);
  transition: all 0.3s;
}

.footer-social a:hover {
  color: var(--accent-primary);
}

.copyright {
  font-size: 0.75rem;
  color: var(--text-muted);
  white-space: nowrap;
}

@media (max-width: 900px) {
  .footer-content {
    flex-direction: column;
    gap: 1.5rem;
    text-align: center;
  }
  
  .footer-left, .footer-right {
    flex-direction: column;
    gap: 1rem;
  }
  
  .footer-nav {
    gap: 1rem;
    flex-wrap: wrap;
    justify-content: center;
  }
}
</style>
