// src/components/Skills.tsx
import React, { useRef } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Monitor, Server, Wrench, Lightbulb, BarChart3, Palette, Users, LayoutDashboard } from 'lucide-react';
import Marquee from './Marquee';

interface Skill {
  name: string;
  icon: any;
  isDevicon: boolean;
}

const containerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.1 }
  }
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" as const } }
};

const SkillItem: React.FC<{ skill: Skill }> = ({ skill }) => {
  return (
    <div className="flex items-center gap-4 group/item cursor-default py-1">
      {/* Fixed icon container for pixel-perfect alignment */}
      <div className="w-8 h-8 flex items-center justify-center shrink-0">
        {skill.isDevicon ? (
          <img 
            src={`https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${skill.icon}/${skill.icon}-original.svg`} 
            alt={skill.name} 
            className="w-7 h-7 grayscale brightness-150 transition-all duration-300 group-hover/item:grayscale-0 group-hover/item:brightness-100 group-hover/item:scale-110 group-hover/item:-translate-y-0.5"
            loading="lazy"
          />
        ) : (
          <span className="text-zinc-500 flex items-center justify-center transition-all duration-300 group-hover/item:text-white group-hover/item:scale-110 group-hover/item:-translate-y-0.5">
            <skill.icon size={22} strokeWidth={2} />
          </span>
        )}
      </div>
      <span className="text-zinc-400 font-medium transition-colors duration-300 group-hover/item:text-white text-[0.95rem] tracking-wide">
        {skill.name}
      </span>
    </div>
  );
};

const Skills: React.FC = () => {
  const containerRef = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start end", "end start"]
  });
  
  const y = useTransform(scrollYProgress, [0, 1], [50, -50]);

  const frontendSkills: Skill[] = [
    { name: 'TypeScript', icon: 'typescript', isDevicon: true },
    { name: 'React', icon: 'react', isDevicon: true },
    { name: 'Vue.js', icon: 'vuejs', isDevicon: true },
    { name: 'React Native', icon: 'react', isDevicon: true },
    { name: 'JavaScript', icon: 'javascript', isDevicon: true },
    { name: 'Tailwind CSS', icon: 'tailwindcss', isDevicon: true },
    { name: 'HTML5', icon: 'html5', isDevicon: true },
    { name: 'CSS3', icon: 'css3', isDevicon: true }
  ];

  const backendSkills: Skill[] = [
    { name: 'Java / Spring', icon: 'java', isDevicon: true },
    { name: '.NET / C#', icon: 'dotnetcore', isDevicon: true },
    { name: 'Docker', icon: 'docker', isDevicon: true },
    { name: 'Node.js', icon: 'nodejs', isDevicon: true },
    { name: 'Python', icon: 'python', isDevicon: true },
    { name: 'PostgreSQL', icon: 'postgresql', isDevicon: true },
    { name: 'SQL', icon: 'mysql', isDevicon: true },
    { name: 'Firebase', icon: 'firebase', isDevicon: true }
  ];

  const toolsSkills: Skill[] = [
    { name: 'Git / GitHub', icon: 'git', isDevicon: true },
    { name: 'Linux', icon: 'linux', isDevicon: true },
    { name: 'Data Analytics', icon: BarChart3, isDevicon: false },
    { name: 'Scrum', icon: LayoutDashboard, isDevicon: false },
    { name: 'Design UI/UX', icon: Palette, isDevicon: false },
    { name: 'Figma', icon: 'figma', isDevicon: true },
    { name: 'Collaboration', icon: Users, isDevicon: false },
    { name: 'Innovation', icon: Lightbulb, isDevicon: false }
  ];

  return (
    <section id="skills" ref={containerRef} className="py-32 relative overflow-hidden">
      {/* Grid Pattern Overlay */}
      <div className="absolute inset-0 bg-grid-pattern mask-fade-y pointer-events-none" />
      {/* Background Marquee */}
      <div className="absolute top-1/2 left-0 -translate-y-1/2 w-full z-0">
        <Marquee text="DEVELOPMENT ARCHITECTURE ENGINEERING " repeat={3} />
      </div>

      <div className="max-w-6xl mx-auto px-8 relative z-10">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
          className="flex flex-col items-center gap-3 mb-16 relative text-center"
        >
          <span className="text-xs text-blue-500 bg-blue-500/10 px-4 py-2 border border-blue-500/20 rounded-full tracking-widest uppercase font-bold backdrop-blur-md">
            Expertise
          </span>
          <h2 className="text-[clamp(2.5rem,6vw,3.5rem)] m-0 leading-tight text-gradient font-heading mix-blend-difference">
            Technical Skills
          </h2>
        </motion.div>
        
        <motion.div 
          style={{ y }}
          variants={containerVariants}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: "-100px" }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          {/* Frontend & Mobile */}
          <motion.div variants={itemVariants} className="glass p-10 rounded-3xl flex flex-col group hover:-translate-y-2 hover:shadow-[0_10px_30px_-10px_rgba(59,130,246,0.15)] hover:border-white/20 transition-all duration-500">
            <div className="flex items-center gap-4 mb-10">
              <span className="text-blue-500 bg-blue-500/10 p-3 rounded-xl flex items-center justify-center">
                <Monitor size={24} />
              </span>
              <h3 className="text-xl m-0 uppercase tracking-wide font-heading">Frontend & Mobile</h3>
            </div>
            <div className="grid grid-cols-2 gap-x-6 gap-y-5">
              {frontendSkills.map(skill => (
                <SkillItem key={skill.name} skill={skill} />
              ))}
            </div>
          </motion.div>

          {/* Backend & Systems */}
          <motion.div variants={itemVariants} className="glass p-10 rounded-3xl flex flex-col group hover:-translate-y-2 hover:shadow-[0_10px_30px_-10px_rgba(59,130,246,0.15)] hover:border-white/20 transition-all duration-500">
            <div className="flex items-center gap-4 mb-10">
              <span className="text-blue-500 bg-blue-500/10 p-3 rounded-xl flex items-center justify-center">
                <Server size={24} />
              </span>
              <h3 className="text-xl m-0 uppercase tracking-wide font-heading">Backend & Systems</h3>
            </div>
            <div className="grid grid-cols-2 gap-x-6 gap-y-5">
              {backendSkills.map(skill => (
                <SkillItem key={skill.name} skill={skill} />
              ))}
            </div>
          </motion.div>

          {/* Tools & More */}
          <motion.div variants={itemVariants} className="glass p-10 rounded-3xl flex flex-col group hover:-translate-y-2 hover:shadow-[0_10px_30px_-10px_rgba(59,130,246,0.15)] hover:border-white/20 transition-all duration-500">
            <div className="flex items-center gap-4 mb-10">
              <span className="text-blue-500 bg-blue-500/10 p-3 rounded-xl flex items-center justify-center">
                <Wrench size={24} />
              </span>
              <h3 className="text-xl m-0 uppercase tracking-wide font-heading">Tools & More</h3>
            </div>
            <div className="grid grid-cols-2 gap-x-6 gap-y-5">
              {toolsSkills.map(skill => (
                <SkillItem key={skill.name} skill={skill} />
              ))}
            </div>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
};

export default Skills;

// src/components/Skills.vue
<template>
  <section id="skills" class="skills section fade-in">
    <div class="section-container">
      <h2 class="section-title"><span>02.</span> Technical Skills</h2>
      
      <div class="skills-grid">
        <!-- Frontend & Mobile -->
        <div class="skill-category card fade-in stagger-item" style="--stagger-delay: 0.1s">
          <div class="category-header">
            <span class="category-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg>
            </span>
            <h3>Frontend & Mobile</h3>
          </div>
          <div class="skill-items">
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" alt="HTML5" title="HTML5">
              <span>HTML5</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" alt="CSS3" title="CSS3">
              <span>CSS3</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" alt="JavaScript" title="JavaScript">
              <span>JavaScript</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" alt="TypeScript" title="TypeScript">
              <span>TypeScript</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" alt="Vue.js" title="Vue.js">
              <span>Vue.js</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" alt="React Native" title="React Native">
              <span>React Native</span>
            </div>
          </div>
        </div>

        <!-- Backend & Systems -->
        <div class="skill-category card fade-in stagger-item" style="--stagger-delay: 0.2s">
          <div class="category-header">
            <span class="category-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
            </span>
            <h3>Backend & Systems</h3>
          </div>
          <div class="skill-items">
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" alt="Java" title="Java">
              <span>Java / Spring</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dotnetcore/dotnetcore-original.svg" alt=".NET" title=".NET">
              <span>.NET / C#</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" alt="SQL" title="SQL">
              <span>SQL</span>
            </div>
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" alt="Node.js" title="Node.js">
              <span>Node.js</span>
            </div>
          </div>
        </div>

        <!-- Tools & Innovation -->
        <div class="skill-category card fade-in stagger-item" style="--stagger-delay: 0.3s">
          <div class="category-header">
            <span class="category-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline><line x1="12" y1="22.08" x2="12" y2="12"></line></svg>
            </span>
            <h3>Tools & More</h3>
          </div>
          <div class="skill-items">
            <div class="skill-item">
              <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" alt="Git" title="Git">
              <span>Git / GitHub</span>
            </div>
            <div class="skill-item">
              <span class="text-icon">🚀</span>
              <span>Innovation</span>
            </div>
            <div class="skill-item">
              <span class="text-icon">📊</span>
              <span>Data Analytics</span>
            </div>
            <div class="skill-item">
              <span class="text-icon">🎨</span>
              <span>Design UI/UX</span>
            </div>
            <div class="skill-item">
              <span class="text-icon">🤝</span>
              <span>Collaboration</span>
            </div>
            <div class="skill-item">
              <span class="text-icon">🔄</span>
              <span>Scrum</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.skills {
  background-color: var(--bg-color);
}

.skills-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 2rem;
}

.skill-category {
  padding: 2rem;
  transition: all var(--transition-base);
}

.skill-category:hover {
  border-color: var(--accent-primary);
  transform: translateY(-5px);
  background: var(--bg-color-alt);
}

.category-header {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 2rem;
}

.category-icon {
  color: var(--accent-primary);
  display: flex;
  align-items: center;
  justify-content: center;
}

.category-header h3 {
  font-size: 1.1rem;
  margin: 0;
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

.skill-items {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1.5rem;
}

.skill-item {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.skill-item img, .text-icon {
  width: 24px;
  height: 24px;
  filter: grayscale(1) brightness(1.5);
  transition: all 0.3s ease;
  display: flex;
  align-items: center;
  justify-content: center;
}

.skill-item:hover img, .skill-item:hover .text-icon {
  filter: grayscale(0) brightness(1);
  transform: scale(1.2);
}

.text-icon {
  font-size: 1.2rem;
}

.skill-item span:not(.text-icon) {
  color: var(--text-secondary);
  font-size: 0.95rem;
  font-weight: 500;
}

@media (max-width: 768px) {
  .skills-grid {
    grid-template-columns: 1fr;
  }
}
</style>
